### ISSUE TITLE
Uncaught TypeError: this.getContainer(...).removeChild is not a function when unmount Stage component

### ISSUE THREAD

**Issue by JMGR2996** [konvajs/react-konva#297]
When I try to return a route back from where the Stage was declared, an exception occurs in the DOM similar to one previously reported when using Jest.

``
konva.js:9583 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at push../node_modules/konva/konva.js.Konva.Stage.destroy (http://localhost:3000/static/js/1.chunk.js:17812:29)
    at Stage.componentWillUnmount (http://localhost:3000/static/js/1.chunk.js:53198:17)
    at callComponentWillUnmountWithTimer (http://localhost:3000/static/js/1.chunk.js:46643:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:30894:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:30943:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:30997:35)
    at safelyCallComponentWillUnmount (http://localhost:3000/static/js/1.chunk.js:46650:9)
    at commitUnmount (http://localhost:3000/static/js/1.chunk.js:46982:15)
    at commitNestedUnmounts (http://localhost:3000/static/js/1.chunk.js:47018:9)
    at unmountHostComponents (http://localhost:3000/static/js/1.chunk.js:47300:11)
    at commitDeletion (http://localhost:3000/static/js/1.chunk.js:47357:9)
    at commitAllHostEffects (http://localhost:3000/static/js/1.chunk.js:48083:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:30894:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:30943:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:30997:35)
    at commitRoot (http://localhost:3000/static/js/1.chunk.js:48258:11)
    at completeRoot (http://localhost:3000/static/js/1.chunk.js:49749:7)
    at performWorkOnRoot (http://localhost:3000/static/js/1.chunk.js:49671:13)
    at performWork (http://localhost:3000/static/js/1.chunk.js:49573:11)
    at performSyncWork (http://localhost:3000/static/js/1.chunk.js:49546:7)
    at requestWork (http://localhost:3000/static/js/1.chunk.js:49423:9)
    at scheduleWork (http://localhost:3000/static/js/1.chunk.js:49227:9)
    at Object.enqueueSetState (http://localhost:3000/static/js/1.chunk.js:42890:9)
    at Router.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/1.chunk.js:68243:20)
    at http://localhost:3000/static/js/1.chunk.js:67267:14
    at listener (http://localhost:3000/static/js/1.chunk.js:6842:24)
    at http://localhost:3000/static/js/1.chunk.js:6860:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (http://localhost:3000/static/js/1.chunk.js:6859:15)
    at setState (http://localhost:3000/static/js/1.chunk.js:6405:23)
    at http://localhost:3000/static/js/1.chunk.js:6438:11
    at Object.confirmTransitionTo (http://localhost:3000/static/js/1.chunk.js:6832:7)
    at handlePop (http://localhost:3000/static/js/1.chunk.js:6436:25)
    at handleHashChange (http://localhost:3000/static/js/1.chunk.js:6426:7)
``

Using:
-  react : 16.6.0
-  react-dom: 16.6.0,
-  react-konva: 16.6.0

**Comment by JMGR2996** [comment]
Fixed installing React Konva

**Comment by JMGR2996** [comment]
Fixed reinstalling React Konva
