### ISSUE TITLE
Konva has no node with the type "Text"

### ISSUE THREAD

**Issue by lusess123** [konvajs/react-konva#415]
VM6191 react-reconciler.development.js:1990 Uncaught Invariant Violation: Konva has no node with the type "Text". If you use minimal version of react-konva, just import required nodes into Konva: `import "konva/lib/shapes/Text"`  If you want to render DOM elements as part of canvas tree take a look into this demo: https://konvajs.github.io/docs/react/DOM_Portal.html
    at invariant (webpack-internal:///./node_modules/react-konva/lib/invariant.js:36:15)
    at createInstance (webpack-internal:///./node_modules/react-konva/lib/ReactKonvaHostConfig.js:116:29)
    at completeWork (webpack-internal:///./node_modules/react-reconciler/cjs/react-reconciler.development.js:10717:28)
    at completeUnitOfWork (webpack-internal:///./node_modules/react-reconciler/cjs/react-reconciler.development.js:14687:16)
    at performUnitOfWork (webpack-internal:///./node_modules/react-reconciler/cjs/react-reconciler.development.js:14660:12)
    at workLoopSync (webpack-internal:///./node_modules/react-reconciler/cjs/react-reconciler.development.js:14625:22)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-reconciler/cjs/react-reconciler.development.js:14188:11)
    at eval (webpack-internal:///./node_modules/react-reconciler/cjs/react-reconciler.development.js:1977:24)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:815:12)
    at runWithPriority (webpack-internal:///./node_modules/react-reconciler/cjs/react-reconciler.development.js:1927:10)

**Comment by lavrton** [comment]
Closing as not enough info.
