### ISSUE TITLE
It doesn't work in CodeSandbox

### ISSUE THREAD

**Issue by ericmasiello** [konvajs/react-konva#585]
I tried copying in the sample code from the README into Codesandbox and I'm seeing a number of errors.

Here's the codesandbox link https://codesandbox.io/s/cocky-hodgkin-9vmok?file=/src/App.js:396-400

Errors:
```
Warning: <Rect /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    at Rect
    at ColoredRect (https://9vmok.csb.app/src/App.js:51:34)
    at div
    at App
Warning: The tag <Rect> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    at Rect
    at ColoredRect (https://9vmok.csb.app/src/App.js:51:34)
    at div
    at App
Warning: React does not recognize the `shadowBlur` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `shadowblur` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at Rect
    at ColoredRect (https://9vmok.csb.app/src/App.js:51:34)
    at div
    at App
```

**Comment by lavrton** [comment]
`<Rect />` is a canvas component. It can not be a child of DOM element such as `<div>`.

In the README you see:

```
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <ColoredRect />
        </Layer>
      </Stage>
```

Rect is places inside a layer.
