### ISSUE TITLE
Nextjs React Konva Error on Yarn Build (ERR_REQUIRE_ESM)

### ISSUE THREAD

**Issue by iamindrazulfi** [konvajs/react-konva#649]
Hello, I have bit question, i was working on react konva on top of Nextjs. 

It was totally working well in Local, but when i tried to Yarn build/npm run build.
it saying .

I have following this step, https://github.com/vercel/next.js/issues/25454
It was work for local, but not when i do build.

```
> Build error occurred
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Project 2022\Mockup Builder\nextds\node_modules\konva\lib\Core.js from D:\Project 2022\Mockup Builder\nextds\node_modules\react-konva\lib\ReactKonvaCore.js not supported.
Instead change the require of Core.js in D:\Project 2022\Mockup Builder\nextds\node_modules\react-konva\lib\ReactKonvaCore.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\Project 2022\Mockup Builder\nextds\node_modules\react-konva\lib\ReactKonvaCore.js:19:13)
    at Object.<anonymous> (D:\Project 2022\Mockup Builder\nextds\node_modules\react-konva\lib\ReactKonva.js:12:23)
    at Object.6605 (D:\Project 2022\Mockup Builder\nextds\.next\server\pages\backend\konva.js:109:18)
    at __webpack_require__ (D:\Project 2022\Mockup Builder\nextds\.next\server\webpack-runtime.js:25:42)
    at D:\Project 2022\Mockup Builder\nextds\.next\server\pages\backend\konva.js:18:69
    at Function.__webpack_require__.a (D:\Project 2022\Mockup Builder\nextds\.next\server\webpack-runtime.js:103:13)
    at Object.607 (D:\Project 2022\Mockup Builder\nextds\.next\server\pages\backend\konva.js:11:21)
    at __webpack_require__ (D:\Project 2022\Mockup Builder\nextds\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (D:\Project 2022\Mockup Builder\nextds\.next\server\pages\backend\konva.js:140:39)
    at D:\Project 2022\Mockup Builder\nextds\.next\server\pages\backend\konva.js:141:66
    at Function.__webpack_require__.X (D:\Project 2022\Mockup Builder\nextds\.next\server\webpack-runtime.js:190:21)
    at D:\Project 2022\Mockup Builder\nextds\.next\server\pages\backend\konva.js:141:47
    at Object.<anonymous> (D:\Project 2022\Mockup Builder\nextds\.next\server\pages\backend\konva.js:144:3)
    at Object.requirePage (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\server\require.js:48:12)
    at Object.loadComponents (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\server\load-components.js:58:23)
    at D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\build\utils.js:591:52
    at Span.traceAsyncFn (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\trace\trace.js:75:26)
    at Object.isPageStatic (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\build\utils.js:587:29)
    at execFunction (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\compiled\jest-worker\processChild.js:1:2826)
    at execHelper (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\compiled\jest-worker\processChild.js:1:2484)
    at execMethod (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\compiled\jest-worker\processChild.js:1:2572)
    at process.messageListener (D:\Project 2022\Mockup Builder\nextds\node_modules\next\dist\compiled\jest-worker\processChild.js:1:1282)  
    at process.emit (node:events:390:28) {
  type: 'Error',
  code: 'ERR_REQUIRE_ESM'
}

```

I am trying to fixing it, but not sure how.
Please help, many Thanks!

**Comment by lavrton** [comment]
Did you look here https://github.com/konvajs/react-konva/issues/588#issuecomment-892895335 ?

**Comment by iamindrazulfi** [comment]
Hey, yes i did, but thats only works on Local, 
It's working good when i do "Yarn dev", but when "Yarn build" its gave me that errors.

**Comment by lavrton** [comment]
Can you create a minimal repository to reproduce the error? Where I can `npm install && npm run build`.

**Comment by lavrton** [comment]
Do not place `react-konva` components inside `pages` folder. Because `next.js` will build every page(file) in your `pages`.

Move that components outside. And then import it. E.g.

```js
const KonvaComponent = dynamic(() => import("../componens/konva"), {
  ssr: false,
})
```

**Comment by antonimarek** [comment]
> Do not place `react-konva` components inside `pages` folder. Because `next.js` will build every page(file) in your `pages`.
> 
> Move that components outside. And then import it. E.g.
> 
> ```js
> const KonvaComponent = dynamic(() => import("../componens/konva"), {
>   ssr: false,
> })
> ```

I wasn't aware of this being the cause of errors. So helpful!!! THANKS! 🚀 😎

**Comment by lavrton** [comment]
Quick not here, it may work right now with the last konva version 9. You may only need to install `canvas` package manually.

```
npm install canvas
```

**Comment by antonimarek** [comment]
In my case that's what I tried first but it didn't help. There were other problems following 😅
