### ISSUE TITLE
Basic jest test fails with `TypeError: Cannot read properties of null (reading 'scale')`

### ISSUE THREAD

**Issue by takanuva15** [konvajs/react-konva#706]
Hi, I am trying to get a super basic jest test working with react-konva, but it seems there is some problem rendering the canvas element called in `Util.createCanvasElement()` within `Konva` since it just keeps throwing this error:

```
Cannot read properties of null (reading 'scale')

TypeError: Cannot read properties of null (reading 'scale')
    at SceneCanvas.setWidth (https://qomkhd.csb.app/node_modules/konva/lib/Canvas.js:57:14)
    at SceneCanvas.setSize (https://qomkhd.csb.app/node_modules/konva/lib/Canvas.js:72:10)
    at new SceneCanvas (https://qomkhd.csb.app/node_modules/konva/lib/Canvas.js:97:10)
    at Stage._buildDOM (https://qomkhd.csb.app/node_modules/konva/lib/Stage.js:644:25)
    at new Stage (https://qomkhd.csb.app/node_modules/konva/lib/Stage.js:89:10)
    at eval (https://qomkhd.csb.app/node_modules/react-konva/es/ReactKonvaCore.js:41:21)
    at commitHookEffectListMount (https://qomkhd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (https://qomkhd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (https://qomkhd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24688:9)
   ...
```

You can reproduce the error by simply going to the "Tests" tab in the below codesandbox:
https://codesandbox.io/s/react-konva-test-demo-qomkhd?file=/src/KonvaDemo.test.tsx

(Alternatively, you can open the codesandbox and download to your local machine via "File->Export to Zip" and then run `npm install` and `npm test`).

Any idea on what configuration I might be missing?

---

For reference (in case you don't want to view the codesandbox), here's the App and Test files:
`KonvaDemo.tsx`:
```
import React from "react";
import { Stage, Layer, Text } from "react-konva";

export default function KonvaDemo() {
  return (
    <>
      <h1>Drawing area</h1>
      <Stage width={window.innerWidth} height={window.innerHeight}>
        <Layer>
          <Text text="Sample text" />
        </Layer>
      </Stage>
    </>
  );
}
```

`KonvaDemo.test.tsx`:
```
import { render, waitFor, screen } from "@testing-library/react";
import Konva from "konva";
import KonvaDemo from "./KonvaDemo";
import * as React from "react";

test("Konva should render one text", async () => {
  const { container } = render(<KonvaDemo />);
  await waitFor(() => screen.getByRole("heading"));

  console.log(Konva.stages[0].find("Text"));

  expect(Konva.stages[0].find("Text")).toHaveLength(1);
});
```

(Thanks for maintaining this awesome library!)

**Comment by lavrton** [comment]
Jest is working in NodeJS environment. And it looks like it can't create 2d canvas context. I am not certain why because `konva` should work in NodeJS. So, I guess somehow browser version is used.

**Comment by takanuva15** [comment]
Interesting. If I download the codesandbox to local, get rid of `jest-canvas-mock`, and then run the test locally it seems to pass so I guess I'll have to run the tests on my local machine. Thanks for your reply!

**Comment by bryantbrock** [comment]
I'm having this error and I'm not using `jest-canvas-mock`. Any other ideas as to the issue? I've tried using different versions of node (16 & 18) and both have this error.

**Comment by takanuva15** [comment]
@bryantbrock are you writing your Jest tests on codesandbox or your local machine? Can you post your error stacktrace?

**Comment by bryantbrock** [comment]
Local machine. It looks like the issue is that konva isn't playing well with `@testing-library/react`. Here's the stack trace, you can see a custom render function I made that is just a simple wrapper around `@testing/library/react`s `render` method, and that seems to be the initiator of the error while the actual blunder is coming from `konva`.

### Code
```tsx
import { render } from '@testUtils';
import { KonvaDemo } from '.';

describe('Components/KonvaDemo', () => {
  it('renders', () => {
    render(<KonvaDemo />);
  });
});
```

### Error
```
Components/KonvaDemo
    ✕ renders (82 ms)

  ● Components/KonvaDemo › renders

    TypeError: Cannot read properties of undefined (reading 'scale')

      47 | const customRender = (ui: React.ReactElement, options?: RenderOptionProps): RenderResult => {
      48 |   const { routerProps, ...rest } = options ?? {};
    > 49 |   return render(ui, {
         |                ^
      50 |     wrapper: (props) => <AppWrapper {...props} routerProps={routerProps} />,
      51 |     ...rest,
      52 |   });

      at SceneCanvas.setWidth (node_modules/konva/konva.js:2197:20)
      at SceneCanvas.setSize (node_modules/konva/konva.js:2213:16)
      at new SceneCanvas (node_modules/konva/konva.js:2268:16)
      at Stage._buildDOM (node_modules/konva/konva.js:6447:31)
      at new Stage (node_modules/konva/konva.js:5831:16)
      at node_modules/react-konva/lib/ReactKonvaCore.js:66:21
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:20573:26)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:20634:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:23426:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:23151:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22990:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22329:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:101:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:97:26)
      at customRender (src/testUtils/index.tsx:49:16)
      at Object.<anonymous> (src/ui/components/KonvaDemo/KonvaDemo.test.tsx:11:11)
```

**Comment by bryantbrock** [comment]
Local machine. It looks like the issue is that konva isn't playing well with `@testing-library/react` or something. Here's the stack trace, you can see a custom render function I made that is just a simple wrapper around `@testing/library/react`s `render` method, and that seems to be the initiator of the error while the actual blunder is coming from `konva`.
### Code
```tsx
import { render } from '@testUtils';
import { KonvaDemo } from '.';
describe('Components/KonvaDemo', () => {
  it('renders', () => {
    render(<KonvaDemo />);
  });
});
```
### Error
```
Components/KonvaDemo
    ✕ renders (82 ms)
  ● Components/KonvaDemo › renders
    TypeError: Cannot read properties of undefined (reading 'scale')
      47 | const customRender = (ui: React.ReactElement, options?: RenderOptionProps): RenderResult => {
      48 |   const { routerProps, ...rest } = options ?? {};
    > 49 |   return render(ui, {
         |                ^
      50 |     wrapper: (props) => <AppWrapper {...props} routerProps={routerProps} />,
      51 |     ...rest,
      52 |   });
      at SceneCanvas.setWidth (node_modules/konva/konva.js:2197:20)
      at SceneCanvas.setSize (node_modules/konva/konva.js:2213:16)
      at new SceneCanvas (node_modules/konva/konva.js:2268:16)
      at Stage._buildDOM (node_modules/konva/konva.js:6447:31)
      at new Stage (node_modules/konva/konva.js:5831:16)
      at node_modules/react-konva/lib/ReactKonvaCore.js:66:21
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:20573:26)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:20634:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:23426:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:23151:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22990:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22329:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:101:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:97:26)
      at customRender (src/testUtils/index.tsx:49:16)
      at Object.<anonymous> (src/ui/components/KonvaDemo/KonvaDemo.test.tsx:11:11)
```

**Comment by takanuva15** [comment]
@bryantbrock Hmm interesting. I was experimenting with it on my local and I got the jest tests to work with Konva. Can you try cloning this repo, running `npm install`, and then `npm test`?
https://github.com/takanuva15/react-konva-jest-demo

(The repo is using redux since I was testing whether Konva tests would work with Redux-driven updates, which does seem to be the case)

**Comment by tlthiem** [comment]
I am having a very similiar issue.

`TypeError: Cannot read properties of undefined (reading 'scale')`.

```
{
  "dependencies": {
    "konva": "9.2.0",
    "react-konva": "17.0.2-6"
  }
  "devDependencies": {
    "@testing-library/react": "12.1.5",
    "canvas": "2.11.2"
  }
}
```

We are stuck with react 17 which is why I need to use outdated react-konva version. Are there any version conflicts I am unaware of?

**Comment by takanuva15** [comment]
@tlthiem I wouldn't know about version conflicts, but if you could reproduce your issue on a fresh sandbox (or just copy my repo but use react 17 instead of 18), that would be very helpful to debug why you're getting an error with jest

**Comment by tlthiem** [comment]
@takanuva15 here is the demo.

https://codesandbox.io/s/react-konva-test-demo-forked-pk8dmd?file=/src/KonvaDemo.test.tsx

```
Cannot read properties of null (reading 'scale')

TypeError: Cannot read properties of null (reading 'scale')
    at SceneCanvas.setWidth (https://pk8dmd.csb.app/node_modules/konva/lib/Canvas.js:57:14)
    at SceneCanvas.setSize (https://pk8dmd.csb.app/node_modules/konva/lib/Canvas.js:72:10)
    at new SceneCanvas (https://pk8dmd.csb.app/node_modules/konva/lib/Canvas.js:97:10)
    at Stage._buildDOM (https://pk8dmd.csb.app/node_modules/konva/lib/Stage.js:644:25)
```

This is the same error i get local.


Thank you for taking a look, that is very kind.
