### ISSUE TITLE
not able to work with react typescript

### ISSUE THREAD

**Issue by aniyy117** [konvajs/react-konva#719]
index.tsx:96 Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_0__.useId is not a function
    at useFiber (index.tsx:96:1)
    at useContextBridge (index.tsx:196:1)
    at StageWrap (ReactKonvaCore.js:28:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at discreteUpdates$1 (react-dom.development.js:22420:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)
useFiber @ index.tsx:96
useContextBridge @ index.tsx:196
StageWrap @ ReactKonvaCore.js:28
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
index.js:1 The above error occurred in the <StageWrap> component:

    at StageWrap (http://localhost:3000/static/js/83.chunk.js:11521:66)
    at FiberProvider (http://localhost:3000/static/js/83.chunk.js:73:1)
    at div
    at ImageTag (http://localhost:3000/static/js/74.chunk.js:6062:95)
    at div
    at div
    at div
    at ModalContent (http://localhost:3000/static/js/66.chunk.js:448797:24)
    at div
    at RefFindNode (http://localhost:3000/static/js/66.chunk.js:21387:94)
    at Ref (http://localhost:3000/static/js/66.chunk.js:21324:24)
    at div
    at RefFindNode (http://localhost:3000/static/js/66.chunk.js:21387:94)
    at Ref (http://localhost:3000/static/js/66.chunk.js:21324:24)
    at PortalInner (http://localhost:3000/static/js/66.chunk.js:433162:81)
    at Portal (http://localhost:3000/static/js/66.chunk.js:432797:81)
    at Modal (http://localhost:3000/static/js/66.chunk.js:448321:81)
    at ImageTaggingModal (http://localhost:3000/static/js/74.chunk.js:6227:60)
    at div
    at ArchProductImageCard (http://localhost:3000/static/js/74.chunk.js:3034:5)
    at ArchImageCardRepeat (http://localhost:3000/static/js/74.chunk.js:2272:5)
    at div
    at div
    at div
    at div
    at AccordionContent (http://localhost:3000/static/js/66.chunk.js:445194:22)
    at div
    at AccordionAccordion (http://localhost:3000/static/js/66.chunk.js:445052:81)
    at Accordion (http://localhost:3000/static/js/66.chunk.js:444936:25)
    at ArchGroupingImage (http://localhost:3000/static/js/74.chunk.js:1059:5)
    at LetSuspense (http://localhost:3000/static/js/main.chunk.js:26401:5)
    at div
    at LetSuspense (http://localhost:3000/static/js/main.chunk.js:26401:5)
    at NewArchCard (http://localhost:3000/static/js/74.chunk.js:4478:98)
    at div
    at div
    at http://localhost:3000/static/js/main.chunk.js:26302:23
    at Route (http://localhost:3000/static/js/66.chunk.js:407947:29)
    at Switch (http://localhost:3000/static/js/66.chunk.js:408116:29)
    at Routes (http://localhost:3000/static/js/main.chunk.js:26634:5)
    at CircuitDiagram (http://localhost:3000/static/js/74.chunk.js:5619:73)
    at Route (http://localhost:3000/static/js/66.chunk.js:407947:29)
    at Switch (http://localhost:3000/static/js/66.chunk.js:408116:29)
    at Routes (http://localhost:3000/static/js/main.chunk.js:26634:5)
    at Suspense
    at main
    at span
    at span
    at Authentication (http://localhost:3000/static/js/main.chunk.js:25655:5)
    at ConnectFunction (http://localhost:3000/static/js/66.chunk.js:405495:75)
    at http://localhost:3000/static/js/main.chunk.js:1587:5
    at http://localhost:3000/static/js/main.chunk.js:26349:107
    at Switch (http://localhost:3000/static/js/66.chunk.js:408116:29)
    at Suspense
    at Router (http://localhost:3000/static/js/66.chunk.js:407619:30)
    at HashRouter (http://localhost:3000/static/js/66.chunk.js:407170:35)
    at Provider (http://localhost:3000/static/js/66.chunk.js:405236:20)
    at AppRouter

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:4012
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react-dom.development.js:11340 Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_0__.useId is not a function
    at useFiber (index.tsx:96:1)
    at useContextBridge (index.tsx:196:1)
    at StageWrap (ReactKonvaCore.js:28:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at discreteUpdates$1 (react-dom.development.js:22420:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)

**Comment by aniyy117** [comment]
It is working fine now, just some version issue

**Comment by dendorferpatrick** [comment]
Hi @aniyy117, I am having the same issue now. What versions resolve the problem for you?

**Comment by aniyy117** [comment]
Which version you are currently using ?

**Comment by dendorferpatrick** [comment]
Thanks for your message. I downgraded to 17.0.2-6 and now it seems to work.
