### ISSUE TITLE
Testing with Jest Snapshot

### ISSUE THREAD

**Issue by IgorGee** [konvajs/react-konva#72]
I'm trying to write some tests with Jest Snapshots. However, when I try to render a component with a Konva stage in it, i get an error. Here's the code in question and the resulting error after running Jest.

```
import React from 'react'
import renderer from 'react-test-renderer'
import Home from './'

describe('<Home />', () => {
  it('renders initial UI', () => {
    const tree = renderer.create(<Home />).toJSON()
    expect(tree).MatchSnapshot()
  })
})
```

`<Home />` contains a `Stage` component.

Here's the resulting error:

```
    TypeError: Cannot read property 'getPooled' of null

      at Object.componentDidMount (node_modules/react-konva/src/react-konva.js:270:61)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.<anonymous> (src/scenes/Home/Home.test.js:7:44)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by benjick** [comment]
I have the same issue

**Comment by jesse-mm** [comment]
As Jest is currently not supported yet; And don't want to raise a new ticket for this. In my use case the test won't start at all because of the following error:

```
TypeError: Konva._nodeCanvas is not a constructor

      at Object.createCanvasElement (node_modules/konva/konva.js:749:11)
      at getDevicePixelRatio (node_modules/konva/konva.js:1250:29)
      at Object.<anonymous>.Konva.SceneCanvas.init (node_modules/konva/konva.js:1291:48)
      at Object.<anonymous>.Konva.SceneCanvas.Object.<anonymous>.Konva.Canvas (node_modules/konva/konva.js:1283:10)
      at new Object.<anonymous>.Konva.SceneCanvas (node_modules/konva/konva.js:1430:18)
      at Object.<anonymous>.Konva.Stage._buildDOM (node_modules/konva/konva.js:10784:27)
      at Object.<anonymous>.Konva.Stage.___init (node_modules/konva/konva.js:10094:12)
      at new Object.<anonymous>.Konva.Stage (node_modules/konva/konva.js:10085:10)
      at Stage.componentDidMount (node_modules/react-konva/lib/index.js:107:19)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:8770:24)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:9946:9)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:542:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:581:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:438:27)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:10050:9)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:11017:42)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:10967:7)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:10878:7)
      at scheduleWorkImpl (node_modules/react-dom/cjs/react-dom.development.js:10732:11)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:10689:12)
      at scheduleTopLevelUpdate (node_modules/react-dom/cjs/react-dom.development.js:11193:5)
      at Object.updateContainer (node_modules/react-dom/cjs/react-dom.development.js:11231:7)
      at node_modules/react-dom/cjs/react-dom.development.js:15226:19
      at Object.unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:11102:12)
      at renderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:15225:17)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:15290:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:218:50)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:98:16)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at mountWithIntl (tests/setupIntl.js:50:715)
      at moodBoardCanvasComponent (src/test/unit/components/CanvasComponentTest.js:71:49)
      at Object.<anonymous> (src/test/unit/components/CanvasComponentTest.js:89:34)
```

This in combination with using enzyme mount.

**Comment by lavrton** [comment]
Can someone create a very simple repository, where we can reproduce and play?

**Comment by lavrton** [comment]
I think it is not failing now. Please add more info if it is still not working.
